### ISSUE TITLE
Display multiple workbenches at the same time

### ISSUE THREAD

**Issue by chenming-wu** [Zolko-123/FreeCAD_aws#2]
HI Zolko, 
Thanks for the wonderful assembly addon! I have seen that in your interface, assembly4 and part design workbenches are shown at the same time, could you please tell how to achieve this? Thanks!
![image](https://user-images.githubusercontent.com/16165404/54406028-c0c94c80-4695-11e9-8269-9cca5fd172fe.png)

**Comment by Zolko-123** [comment]
Oups, I hadn't seen your message. It that time, Asm4 was not a workbench, it was a collection of macros. But your right, it would be good to be able to display 2 workbenches.
